spring:
  cloud:
    gateway:
      routes:
      - id: managecurrencyconversionfactor
        uri: lb://managecurrencyconversionfactor
        predicates:
        - Path=/conversionfactor/**,/h2
      - id: convertcurrency
        uri: lb://convertcurrency
        predicates:
        - Path=/currency/**
        
cloudapigateway.zipkin.url: http://zipkin:9411/
cloudapigateway.eureka.url: http://eureka:8761/eureka